const TYPES = {
  INIT_SEARCH: 'INIT_SEARCH',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
  GET_MAIN_TRACK: 'GET_MAIN_TRACK',
  GET_MAIN_INFO: 'GET_MAIN_INFO',
  GET_MAIN_KEY: 'GET_MAIN_KEY'
};

export default TYPES;