const TYPES = {
  INIT_SEARCH: 'INIT_SEARCH',
  INIT_SEARCH_INFO: 'INIT_SEARCH_INFO',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
  GET_MAIN_TRACK: 'GET_MAIN_TRACK',
  GET_MAIN_INFO: 'GET_MAIN_INFO',
  GET_MAIN_KEY: 'GET_MAIN_KEY',
  GET_HARMONIC_KEYS: 'GET_HARMONIC_KEYS',
  GET_ALL_SIMILAR: 'GET_ALL_SIMILAR',
  ALL_SIMILAR_INFO: 'ALL_SIMILAR_INFO',
  ADD_TO_PLAYLIST: 'ADD_TO_PLAYLIST',
  GET_PLAYLIST: 'GET_PLAYLIST',
  DELETE_FROM_PLAYLIST: 'DELETE_FROM_PLAYLIST',
  CLEAR_PLAYLIST: 'CLEAR_PLAYLIST',
  TOGGLE_CAMELOT: 'TOGGLE_CAMELOT',
  GO_BACK: 'GO_BACK',
};

export default TYPES;